/* 
 * File:   Interrupt_Generation_Confg.h
 * Author: abdo
 *
 * Created on April 14, 2024, 4:02 AM
 */

#ifndef INTERRUPT_GENERATION_CONFG_H
#define	INTERRUPT_GENERATION_CONFG_H

#define PRIORITY_FEATURE_DISABLE  0
#define PRIORITY_FEATURE_ENABLE   1

#define EXTERNAL_FEATURE_DISABLE  0
#define EXTERNAL_FEATURE_ENABLE   1

#define INTERRUPT_FEATURE_DISABLE  0
#define INTERRUPT_FEATURE_ENABLE   1

//#define INTERRUPT_PRIORITY_LEVELS  PRIORITY_FEATURE_ENABLE 

#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE      EXTERNAL_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_onChange_FEATURE_ENABLE  EXTERNAL_FEATURE_ENABLE

#define ADC_INTERRUPT_FEATURE                          INTERRUPT_FEATURE_ENABLE
#define TIMER0_INTERRUPT_FEATURE                       INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE                       INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE                       INTERRUPT_FEATURE_ENABLE
#define TIMER3_INTERRUPT_FEATURE                       INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_FEATURE                         INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE                         INTERRUPT_FEATURE_ENABLE

#define EUSART_TX_INTERRUPT_FEATURE                    INTERRUPT_FEATURE_ENABLE
#define EUSART_RX_INTERRUPT_FEATURE                    INTERRUPT_FEATURE_ENABLE

#define MSSP_SPI_INTERRUPT_FEATURE                     INTERRUPT_FEATURE_ENABLE

#define MSSP_I2C_INTERRUPT_FEATURE                     INTERRUPT_FEATURE_ENABLE
#define MSSP_I2C_BUS_COLLISION_INTERRUPT_FEATURE       INTERRUPT_FEATURE_ENABLE

#endif	/* INTERRUPT_GENERATION_CONFG_H */

